config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/create'

  delete 'sessions/destroy'

  resources :users
  resources :products do
    get :who_bought, on: :member
  end  

  scope '(:locale)' do 
    resources :line_items
    resources :carts
    resources :orders
    root 'store#index', as: 'store', via: :all
  end 

 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_product(product_id)
		current_item = line_items.where(product_id: product_id).first
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end	
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
	belongs_to :order
	
	def total_price
		product.price * quantity
	end	
end

app/models/order.rb
class Order < ActiveRecord::Base

	PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

	validates :name, :address, :email, :pay_type, presence: true
	validates :pay_type, inclusion: PAYMENT_TYPES

	has_many :line_items, dependent: :destroy

	def add_line_items_from_cart(cart)
		cart.line_items.each do|item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/product.rb
class Product < ActiveRecord::Base

	default_scope {order('title')}
	has_many :line_items
	has_many :orders, through: :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

	validates :title, :description, :image_url, presence: true 
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true
	validates :image_url, format: {
		with: %r{\.(gif|jpg|png)}i,
		message: "Must be a URL for JPG,GIF or PNG image"
	}

	private

  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
 	# after_destroy :ensure_an_admin_remains
  validates :name, presence: true, uniqueness: true
  has_secure_password
  # def ensure_an_admin_remains
  # 	if User.count.zero?
  # 		raise "Can't delete last user"
  # 	end
  # end	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
  	@total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	skip_before_action :authorize, only: [:create, :update, :destroy]
	def new
		@cart = Cart.new
	end

	def show
		begin
			@cart = Cart.find(params[:id])
			rescue ActiveRecord::RecordNotFound
			logger.error "Attempt to access invalid cart #{params[:id]}"
			redirect_to store_path, notice: 'Invalid cart'
			else
				respond_to do |format|
				format.html # show.html.erb
				format.xml { render xml: @cart }
			end
		end	
	end

	def destroy
		@cart = current_cart
		@cart.destroy
		session[:cart_id]=nil
		respond_to do |format|
			format.html { redirect_to store_path}
			format.xml { head :ok }
		end
	end

	private

	def invalid_cart
		logger.error "attempt to access invalid cart #{params[:id]}"
		redirect_to store_path, notice: "Invalid cart"
	end	 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	skip_before_action :authorize, only: [:new, :create]
	def new
		@cart = current_cart
		if @cart.line_items.empty?
			redirect_to store_path, notice: "Your cart is empty."
			return
		end
		@order = Order.new
		respond_to do |format|
			format.html # new.html.erb
			format.xml { render xml: @order }
		end	
	end

	def create
	 	@order = Order.new(param_values)
	 	@order.add_line_items_from_cart(current_cart)
	 	respond_to do |format|
	 		if @order.save
	 			Cart.destroy(session[:cart_id])
	 			session[:cart_id] = nil
	 			#byebug
	 			OrderNotifier.received(@order).deliver
				format.html {redirect_to(store_path, notice: I18n.t(:thanks))}
 				format.xml { render xml: @order, status: :created, location: @order }
			else 
				format.html {render action: "new"}	
				format.xml { render xml: @order.errors, status: :unprocessable_entity }
	 		end
	 	end	
	end
		
	def param_values
		params.require(:order).permit(:name, :address, :email, :pay_type )		
	end

end	

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  def index
    if params[:set_locale]
      redirect_to store_url(locale: params[:set_locale])
    else
      @product = Product.all
      @cart = current_cart
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
	end
	
	def new
		@user = User.new
	end
		
	def create
		@user = User.new(user_params)	
		respond_to do |format|
			if @user.save
				format.html { redirect_to users_path,
				notice: "User #{@user.name} was successfully created." }
				format.json { render action: 'show', status: :created, location: @user }
			else
				format.html { render action: 'new'}
				format.json { render json: @user.errors, status: :unprocessable_entity }	
			end	
		end	
	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		respond_to do |format|
			if @user.update(user_params)
				format.html { redirect_to users_path, notice: "User #{@user.name} was successfully updated." }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end
				
	def index
		@user = User.order(:name)
	end

	def destroy
    @user = User.find(params[:id])
    # begin
    	if @user.id == session[:user_id]
    		flash[:notice] = "Can't destroy current user"
    	else	
      	@user.destroy
      	flash[:notice] = "User #{@user.name} deleted"
      end	
    # rescue StandardError => e
    #   flash[:notice] = e.message
    # end
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  				
	def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def hidden_div_if(condition, attributes = {}, &block)
		#debugger
		if condition
		attributes["style"] = "display: none"
		end
		content_tag("div", attributes, &block)
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<body id="store" >
	<div id="banner" >
		<%= form_tag store_path, class: 'locale' do %>
			<%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s),
			onchange: 'this.form.submit()' %>
			<%= submit_tag 'submit' %>
			<%= javascript_tag "$('.locale input').hide()" %>
		<% end %>
		<%= image_tag("logo.png") %>
		<%= @page_title || t(:title) %>
	</div>
	<div id="columns" >
		<div id="side" >
			<div id="cart" >
				<% if @cart %>	
					<%= hidden_div_if(@cart.line_items.empty?, id: "cart") do %>
						<%= render @cart %>
					<% end %>
				<% end %>	
			</div>	
		<a href="http://localhost:3000" ><%= t(:home) %></a><br />
		<a href="http://www..../faq" ><%= t(:questions) %></a><br />
		<a href="http://www..../news" ><%= t(:news) %></a><br />
		<a href="http://www..../contact" ><%= t(:contact) %></a><br />
		<% if session[:user_id] %>
			<ul>
				<li><%= link_to 'Orders', orders_path %></li>
				<li><%= link_to 'Products', products_path %></li>
				<li><%= link_to 'Users', users_path %></li>
			</ul>
			<%= button_to 'Logout', logout_path, method: :delete %>
		<% end %>
		<p><%= Time.now.strftime("%T") %></p>
		</div>
			<div id="main" >
				<%= yield %>
			</div>
	</div>
</body>
</html>

app/views/order_notifier/received.html.erb
<h1>OrderNotifier#received</h1>

<p>
  <%= @greeting %>, find me in app/views/order_notifier/received.html.erb
</p>

app/views/order_notifier/received.text.erb
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items -%>
We'll send you a separate e-mail when your order ships.

app/views/order_notifier/shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
This is just to let you know that we've shipped your recent order:
</p>
<table>
	<tr><th colspan="2">Qty</th><th>Description</th></tr>
	<%= render @order.line_items -%>
</table>

app/views/order_notifier/shipped.text.erb
OrderNotifier#shipped

<%= @greeting %>, find me in app/views/order_notifier/shipped.text.erb